services:
  backend:
    image: ghcr.io/sinaptik-ai/panda-agi/panda-agi-ui:main-backend
    container_name: panda-agi-backend
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8080:8080"
      - "2664:2664"
    environment:
      - PYTHONPATH=/app
      - WORKSPACE_PATH=./workspace
      - FASTAPI_RELOAD=false
      - ENV=${ENV:-local}
      - PANDA_AGI_BASE_URL=https://agi-api.pandas-ai.com
    volumes:
      - ./workspace:/app/workspace
    networks:
      - panda-agi-network
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    image: ghcr.io/sinaptik-ai/panda-agi/panda-agi-ui:main-frontend
    container_name: panda-agi-frontend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8001}
      - NEXT_PUBLIC_USE_AUTH=${NEXT_PUBLIC_USE_AUTH:-false}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - panda-agi-network
    restart: unless-stopped
    env_file:
      - .env

networks:
  panda-agi-network:
    driver: bridge

volumes:
  workspace:
